default_location: Melbourne, Victoria, Australia
default_locale: en
max_search_distance: 150
default_search_distance: 5

types:
  - Karma
  - Trade
  - Sale
  - Hire

categories:
    Art:
      - Prints
      - Paintings
      - Jewelry
    Books:
      - Fiction
      - Non-Fiction
      - Fantasy
      - Science Fiction
      - Textbooks
    Computer & Electronics:
      - Laptops
      - Desktops
      - Phones
    Clubs:
      - Politics
      - Sports
      - Magick
    Tools:
      - Electronics
      - Home/Garden
      - Kitchen
    Video Games:
      - Nintendo 3DS
      - Nintendo Switch
    Services:
      - Software Development
      - Graphic Design
      - Tutors
    Personals:
      - Dating
      - Friends
    Other:
      - Information
      - Alerts & Warnings
