default_location: Melbourne, Victoria, Australia

types:
  - Karma
  - Trade
  - Loan
  - Sale
  - Hire
  - Info
  - Seeking

categories:
    Books:
      - Fiction
      - Non-Fiction
      - Fantasy
      - Science Fiction
      - Textbooks
    Computer & Electronics:
      - Laptops
      - Desktops
      - Phones
    Clubs:
      - Politics
      - Sports
    Tools:
      - Electronics
      - Home/Garden
      - Kitchen
    Video Games:
      - Nintendo 3DS
      - Nintendo Switch
    Services:
      - Software Development
      - Graphic Design
      - Tutors
    Personals:
      - Dating
    Other:
      - Information
      - Alerts & Warnings
