# config/meta.yml

meta_product_name: "Classifeds"
meta_title: "Classifeds - On the Fediverse"
meta_description: "Federated Classified Ads"
meta_image: "https://picsum.photos/1024/768?random="
twitter_account: "@product_twitter_account"   # required for Twitter Cards
